name:                qafny-hs
version:             0.1.0.0
github:              "githubuser/qafny-hs"
license:             GPL
author:              ---
maintainer:          ---
copyright:           ---

extra-source-files:
- README.org
- CHANGELOG.md

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Qafny Program Verifier

dependencies:
- base >= 4.7 && < 5
- array
- mtl
- lens
- text
- containers
- fused-effects
- fused-effects-lens
- recursion-schemes


ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -Wno-unused-matches
- -Wno-missing-export-lists
- -Wno-unused-top-binds

library:
  source-dirs: src

build-tools:
- happy
- alex

executables:
  qafny-hs-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qafny-hs

tests:
  qafny-hs-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - qafny-hs
    - tasty
    - tasty-hunit
