#+TITLE: Proposal: Higher-Order Entanglement Type
#+LATEX_HEADER_EXTRA: \input{~/template/semantics}


* Introduction

=EN= type is not expressive enough for Quantum Fourier Transformation. Consider
an arbitrary 2-range locus ={ x[0..n], y[0..m] }=. Applying QFT to \(\ket{x}\)
is equivalent to
# 
#+begin_export latex
\begin{align*}
  \sum_{i \in S} \alpha_i \omega(p_i, N) \ket{x_i}\ket{y_i}
  & \mapsto
    \frac{1}{\sqrt{N}}
    \sum_{i \in S}\sum_{k = 0}^{N - 1}
    \alpha_i\omega(p_i + x_i k, N) \ket{k}\ket{y_i}
  \\
  & =
    \frac{1}{\sqrt{N}}
    \sum_{k = 0}^{N - 1} \ket{k}\prs{\alpha_i\sum_{i \in S} \omega(p_i + x_i k, N)\ket{y_i}} 
\end{align*}
#+end_export
# 
which generalizes the semantics of =EN= type using amplitudes, a lower-level
=EN= representation and a sequence of basis ket induced by a Qft operation
#
\[
\denote{\mathtt{EN}}_{n+1} =
\mathtt{seq\ags{nat}} \times
\denote{\mathtt{EN}}_{n} \times
\mathtt{seq\ags{nat}} 
\]
where
\[
\denote{\mathtt{EN}}_{0} = \mathtt{seq\ags{nat}} \times \mathtt{nat}
\]
standing for the exponents of a given root of unity's power. 

Given \(\mathtt{EN}_{n+1}\), measuring the range corresponding to the tailing
kets lowers the type to  \(\mathtt{EN}_{n}\). 
# 
However, when measuring the range corresponding to the inner representation, the
order doesn't reduce until the inner representation's order is reduced.
#
In anoter words, if an \(\mathtt{EN}_{n+1}\) representation demotes to
 \(\mathtt{EN}_{n}\), the entire representation demotes from
 \(\mathtt{EN}_{n+2}\) to  \(\mathtt{EN}_{n+1}\).

#
Higher-order entanglement type, or the universe of entanglement type, may be too
powerful. Here are two useful instantiation.
# 
- \(\mathtt{EN}_1\) is identical to the current =EN=.
- \(\mathtt{EN}_2\) can be named as =Qft= type that corresponds to outcome of a
  =Qft= application.

